
- name: NGINX | Installing Epel
  yum:
    name: epel-release
    state: present
 
- name: NGINX | Installing NGINX
  yum:
    name: nginx
    state: latest
 
- name: NGINX | Starting NGINX
  service:
    name: nginx
    state: started